name: formapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.0
  http: ^0.13.6
  intl: ^0.17.0
  flutter_local_notifications: ^12.0.4
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.3

dependency_overrides:
  http: ^0.13.6

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Rate form-.png"

flutter:
  uses-material-design: true
  assets:
    - assets/Rate form_transparent-.png
    - assets/Rate form-.png

